join-message: "This is from Task Master Plugin - Hi %name%"
# zh_cn fr_fr ja_jp en_us ko_kr (chinese, french, japanese, english, korean)
language: zh_cn
refresh-while-join: false
game-status: false
block-probability-weight: 19
entity-hunt-probability-weight: 19
have-item-probability-weight: 19
death-type-probability-weight: 19
complete-advancement-probability-weight: 19
type-chat-probability-weight: 5
block-weight: 1
entity-weight: 1
have-item-weight: 1
death-type-weight: 1
complete-advancement-weight: 1
player-chat-weight: 1
game-target-points: 30
